/*
 * generated by Xtext
 */
package org.xmdl.outline;

import java.util.List;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.ui.common.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;
import org.xmdl.wdl.Model;
import org.xmdl.wdl.SimpleType;
import org.xmdl.wdl.Type;

/**
 * customization of the default outline structure
 * 
 */
public class WDLTransformer extends AbstractDeclarativeSemanticModelTransformer {

	public List<Type> getChildren(Model model) {
		return model.getTypes();
	}

	public List<EObject> getChildren(SimpleType attribute) {
		return NO_CHILDREN;
	}
}
