/*
 * generated by Xtext
 */
package org.xmdl;

/**
 * Use this class to register components to be used within the IDE.
 */
public class WDLRuntimeModule extends org.xmdl.AbstractWDLRuntimeModule {

}
