/*
* generated by Xtext
*/
package org.xmdl.contentassist;

import org.xmdl.contentassist.AbstractWDLProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class WDLProposalProvider extends AbstractWDLProposalProvider {

}
