/*
 * generated by Xtext
 */
package org.xmdl.labeling;

import java.util.List;

import org.eclipse.xtext.ui.core.DefaultLabelProvider;
import org.xmdl.wdl.Attribute;
import org.xmdl.wdl.Embed;
import org.xmdl.wdl.Entity;
import org.xmdl.wdl.Enumeration;
import org.xmdl.wdl.EnumerationLiteral;
import org.xmdl.wdl.Model;
import org.xmdl.wdl.Project;
import org.xmdl.wdl.Query;
import org.xmdl.wdl.QueryParameter;
import org.xmdl.wdl.SimpleType;
import org.xmdl.wdl.Type;
import org.xmdl.wdl.gen.utils.ExtensionUtils;

/**
 * see
 * http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class WDLLabelProvider extends DefaultLabelProvider {
	public String image(Type x) {
		return "full/obj16/SimpleType.gif";
	}

	public String image(Model x) {
		return "full/obj16/Model.gif";
	}

	public String image(Project x) {
		return "full/obj16/Project.gif";
	}

	public String image(SimpleType type) {
		return "full/obj16/SimpleType.gif";
	}

	public String image(Entity x) {
		if (ExtensionUtils.isChild(x))
			return "full/obj16/EntityChild.gif";
		return "full/obj16/Entity.gif";
	}

	public String image(Enumeration x) {
		return "full/obj16/Enumeration.gif";
	}

	public String image(Embed x) {
		return "full/obj16/Embed.gif";
	}

	public String image(EnumerationLiteral x) {
		return "full/obj16/EnumerationLiteral.gif";
	}

	public String image(Query x) {
		return "full/obj16/Query.gif";
	}

	public String image(QueryParameter x) {
		return "full/obj16/QueryParameter.gif";
	}

	public String image(Attribute x) {
		Type type = x.getType();
		if (ExtensionUtils.isChild(x))
			return "full/obj16/AttributeMaster.gif";
		if (ExtensionUtils.isMaster(x))
			return "full/obj16/AttributeChild.gif";
		if (ExtensionUtils.isEmbed(type))
			return "full/obj16/AttributeEmbed.gif";
		if (ExtensionUtils.isReference(type))
			return "full/obj16/AttributeReference.gif";
		if (ExtensionUtils.isBasic(type))
			return "full/obj16/AttributeSimpleType.gif";
		return "full/obj16/Attribute.gif";
	}

	public String text(Attribute x) {
		StringBuffer sb = new StringBuffer();
		sb.append(x.getName());
		Type type = x.getType();
		if (type != null) {
			sb.append(" : ").append(type.getName());
		}
		Attribute opp = ExtensionUtils.opposite(x);
		if (opp != null) {
			Type t = (Type) opp.eContainer();
			if (t != null) {
				sb.append(" -> ");
				sb.append(t.getName()).append(".").append(opp.getName());
			}
		}
		return sb.toString();
	}

	public String text(Model x) {
		StringBuffer sb = new StringBuffer();
		Project project = x.getProject();
		if (project != null && project.getName() != null) {
			sb.append(project.getName());
			String basePackage = project.getBasePackage();
			if (basePackage != null) {
				sb.append(" (").append(basePackage).append(")");
			}
		} else {
			sb.append("Model");
		}
		return sb.toString();
	}

	public String text(EnumerationLiteral x) {
		StringBuffer sb = new StringBuffer();
		sb.append(x.getOrdinal());
		sb.append(" : ").append(x.getName());
		return sb.toString();
	}
	
	public String text(Query x) {
		StringBuffer sb = new StringBuffer();
		sb.append(x.getName());
		sb.append(" <");
		List<Entity> entities = x.getEntities();
		for (int i = 0; i < entities.size(); i++) {
			Entity e = entities.get(i);
			if (i != 0)
				sb.append(", ");
			sb.append(e.getName());
		}
		sb.append(">");
		return sb.toString();
	}

	public String text(QueryParameter x) {
		StringBuffer sb = new StringBuffer();
		sb.append(x.getName());
		Type type = x.getType();
		if (type != null) {
			sb.append(" : ").append(type.getName());
		}
		return sb.toString();
	}
}
