#!/bin/bash
mvn install:install-file  -Dpackaging=jar -DgeneratePom=true -DcreateChecksum=true -DgroupId=org.xmdl.wdl.gen -Dfile=../org.xmdl.wdl.taslak/generator/com.google.collect_0.8.0.v200907171100.jar                    -DartifactId=com.google.collect                 -Dversion=0.8.0.v200907171100
mvn install:install-file  -Dpackaging=jar -DgeneratePom=true -DcreateChecksum=true -DgroupId=org.xmdl.wdl.gen -Dfile=../org.xmdl.wdl.taslak/generator/org.eclipse.emf.ecore.xmi_2.5.0.v200906151043.jar             -DartifactId=org.eclipse.emf.ecore.xmi          -Dversion=2.5.0.v200906151043
mvn install:install-file  -Dpackaging=jar -DgeneratePom=true -DcreateChecksum=true -DgroupId=org.xmdl.wdl.gen -Dfile=../org.xmdl.wdl.taslak/generator/org.eclipse.xtend.typesystem.emf_0.7.1.v200907170713.jar      -DartifactId=org.eclipse.xtend.typesystem.emf   -Dversion=0.7.1.v200907170713
mvn install:install-file  -Dpackaging=jar -DgeneratePom=true -DcreateChecksum=true -DgroupId=org.xmdl.wdl.gen -Dfile=../org.xmdl.wdl.taslak/generator/com.google.guice_1.0.1.v200907171100-aopalliance.jar          -DartifactId=com.google.guice-aopalliance       -Dversion=1.0.1.v200907171100
mvn install:install-file  -Dpackaging=jar -DgeneratePom=true -DcreateChecksum=true -DgroupId=org.xmdl.wdl.gen -Dfile=../org.xmdl.wdl.taslak/generator/com.google.guice_1.0.1.v200907171100-guice-1.0_patched.jar    -DartifactId=com.google.guice-guice-1.0_patched -Dversion=1.0.1.v200907171100
mvn install:install-file  -Dpackaging=jar -DgeneratePom=true -DcreateChecksum=true -DgroupId=org.xmdl.wdl.gen -Dfile=../org.xmdl.wdl.taslak/generator/org.eclipse.emf.mwe.core_0.7.1.v200907170432.jar              -DartifactId=org.eclipse.emf.mwe.core           -Dversion=0.7.1.v200907170432
mvn install:install-file  -Dpackaging=jar -DgeneratePom=true -DcreateChecksum=true -DgroupId=org.xmdl.wdl.gen -Dfile=../org.xmdl.wdl.taslak/generator/org.eclipse.xtend.util.stdlib_0.7.1.v200907170713.jar         -DartifactId=org.eclipse.xtend.util.stdlib      -Dversion=0.7.1.v200907170713
mvn install:install-file  -Dpackaging=jar -DgeneratePom=true -DcreateChecksum=true -DgroupId=org.xmdl.wdl.gen -Dfile=../org.xmdl.wdl.taslak/generator/com.ibm.icu_4.0.1.v20090415.jar                               -DartifactId=com.ibm.icu                        -Dversion=4.0.1.v20090415
mvn install:install-file  -Dpackaging=jar -DgeneratePom=true -DcreateChecksum=true -DgroupId=org.xmdl.wdl.gen -Dfile=../org.xmdl.wdl.taslak/generator/org.eclipse.emf.mwe.utils_0.7.1.v200907170432.jar             -DartifactId=org.eclipse.emf.mwe.utils          -Dversion=0.7.1.v200907170432
mvn install:install-file  -Dpackaging=jar -DgeneratePom=true -DcreateChecksum=true -DgroupId=org.xmdl.wdl.gen -Dfile=../org.xmdl.wdl.taslak/generator/org.eclipse.xtext_0.7.1.v200907171100.jar                     -DartifactId=org.eclipse.xtext                  -Dversion=0.7.1.v200907171100
mvn install:install-file  -Dpackaging=jar -DgeneratePom=true -DcreateChecksum=true -DgroupId=org.xmdl.wdl.gen -Dfile=../org.xmdl.wdl.taslak/generator/org.antlr.runtime_3.0.0.v200803061811.jar                     -DartifactId=org.antlr.runtime                  -Dversion=3.0.0.v200803061811
mvn install:install-file  -Dpackaging=jar -DgeneratePom=true -DcreateChecksum=true -DgroupId=org.xmdl.wdl.gen -Dfile=../org.xmdl.wdl.taslak/generator/org.eclipse.equinox.common_3.5.0.v20090520-1800.jar           -DartifactId=org.eclipse.equinox.common         -Dversion=3.5.0.v20090520-1800
mvn install:install-file  -Dpackaging=jar -DgeneratePom=true -DcreateChecksum=true -DgroupId=org.xmdl.wdl.gen -Dfile=../org.xmdl.wdl.taslak/generator/org.eclipse.xtext.log4j_1.2.15.v200907171100.jar              -DartifactId=org.eclipse.xtext.log4j            -Dversion=1.2.15.v200907171100
mvn install:install-file  -Dpackaging=jar -DgeneratePom=true -DcreateChecksum=true -DgroupId=org.xmdl.wdl.gen -Dfile=../org.xmdl.wdl.taslak/generator/org.apache.commons.cli_1.0.0.v20080604-1500.jar               -DartifactId=org.apache.commons.cli             -Dversion=1.0.0.v20080604-1500
mvn install:install-file  -Dpackaging=jar -DgeneratePom=true -DcreateChecksum=true -DgroupId=org.xmdl.wdl.gen -Dfile=../org.xmdl.wdl.taslak/generator/org.eclipse.jdt.core_3.5.0.v_963.jar                          -DartifactId=org.eclipse.jdt.core               -Dversion=3.5.0.v_963
mvn install:install-file  -Dpackaging=jar -DgeneratePom=true -DcreateChecksum=true -DgroupId=org.xmdl.wdl.gen -Dfile=../org.xmdl.wdl.taslak/generator/org.eclipse.xtext.util_0.7.1.v200907171100.jar                -DartifactId=org.eclipse.xtext.util             -Dversion=0.7.1.v200907171100
mvn install:install-file  -Dpackaging=jar -DgeneratePom=true -DcreateChecksum=true -DgroupId=org.xmdl.wdl.gen -Dfile=../org.xmdl.wdl.taslak/generator/org.apache.commons.logging_1.1.1.v200904062255.jar            -DartifactId=org.apache.commons.logging         -Dversion=1.1.1.v200904062255
mvn install:install-file  -Dpackaging=jar -DgeneratePom=true -DcreateChecksum=true -DgroupId=org.xmdl.wdl.gen -Dfile=../org.xmdl.wdl.taslak/generator/org.eclipse.text_3.5.0.v20090513-2000.jar                     -DartifactId=org.eclipse.text                   -Dversion=3.5.0.v20090513-2000
mvn install:install-file  -Dpackaging=jar -DgeneratePom=true -DcreateChecksum=true -DgroupId=org.xmdl.wdl.gen -Dfile=../org.xmdl.wdl.taslak/generator/org.eclipse.emf.common_2.5.0.v200906151043.jar                -DartifactId=org.eclipse.emf.common             -Dversion=2.5.0.v200906151043
mvn install:install-file  -Dpackaging=jar -DgeneratePom=true -DcreateChecksum=true -DgroupId=org.xmdl.wdl.gen -Dfile=../org.xmdl.wdl.taslak/generator/org.eclipse.xpand_0.7.1.v200907170713.jar                     -DartifactId=org.eclipse.xpand                  -Dversion=0.7.1.v200907170713
mvn install:install-file  -Dpackaging=jar -DgeneratePom=true -DcreateChecksum=true -DgroupId=org.xmdl.wdl.gen -Dfile=../org.xmdl.wdl.taslak/generator/org.eclipse.emf.ecore_2.5.0.v200906151043.jar                 -DartifactId=org.eclipse.emf.ecore              -Dversion=2.5.0.v200906151043
mvn install:install-file  -Dpackaging=jar -DgeneratePom=true -DcreateChecksum=true -DgroupId=org.xmdl.wdl.gen -Dfile=../org.xmdl.wdl.taslak/generator/org.eclipse.xtend_0.7.1.v200907170713.jar                     -DartifactId=org.eclipse.xtend                  -Dversion=0.7.1.v200907170713
mvn install:install-file  -Dpackaging=jar -DgeneratePom=true -DcreateChecksum=true -DgroupId=org.xmdl.wdl.gen -Dfile=../org.xmdl.wdl.taslak/generator/org.xmdl.wdl.ida_0.7.0.20090816_alpha1.jar                    -DartifactId=org.xmdl.wdl.ida                   -Dversion=0.7.0.20090816_alpha1
mvn install:install-file  -Dpackaging=jar -DgeneratePom=true -DcreateChecksum=true -DgroupId=org.xmdl.wdl.gen -Dfile=../org.xmdl.wdl.taslak/generator/org.xmdl.wdl_0.7.0.20090816_alpha1.jar                        -DartifactId=org.xmdl.wdl                       -Dversion=0.7.0.20090816_alpha1
mvn install:install-file  -Dpackaging=jar -DgeneratePom=true -DcreateChecksum=true -DgroupId=org.xmdl.wdl.gen -Dfile=../org.xmdl.wdl.taslak/generator/org.xmdl.wdl.generator_0.7.0.20090816_alpha1.jar              -DartifactId=org.xmdl.wdl.generator             -Dversion=0.7.0.20090816_alpha1

cp -a -u ~/.m2/repository/org/xmdl/wdl/gen/ ../repository/org/xmdl/wdl/
